version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: hotel-booking-system
      DB_USERNAME: root
      DB_PASSWORD: hotelbooking
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80" # Ánh xạ cổng 80 của host tới cổng 80 của container
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Ánh xạ cấu hình Nginx
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hotel-booking-system
      MYSQL_USER: root
      MYSQL_PASSWORD: hotelbooking
      MYSQL_ROOT_PASSWORD: hotelbooking # Đổi mật khẩu root này
    volumes:
      - dbdata:/var/lib/mysql # Lưu trữ dữ liệu cơ sở dữ liệu
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local